### ISSUE TITLE
[CMSCore] Navigation in Website edition

### ISSUE THREAD

**Issue by nicolas-bastien** [prestaconcept/open-source-management#2]
CMS architecture has been made for small website.

Has time goes we are limited by this choice.

Navigation (menu and menu item edition) has to be moved in website edition.

By doing this content management and frontend navigation will be clearly decoupled.

Spec : 
- refactor website translation in sidemenu
- add a navigation tab on website admin (like on cmf sandbox element tab)
- there will be only one menu for a website : /website/sandbow/menu/main
- override jstree action to open ev erything in a modal like in block edition

**Comment by nicolas-bastien** [comment]
Rework Menu fixtures

Remove old single spage menu + add a configuration like in_navigation to set if a page should be attache to a menu item or not

**Comment by aflaus-presta** [comment]
- add a navigation tab on website admin (like on cmf sandbox element tab) => **OK**
- there will be only one menu for a website : /website/sandbow/menu/main  => **OK**
- override jstree action to open everything in a modal like in block edition => **functional only**
  _currently jstree action are opened in an iframe (that cause problem for action redirection and layout is always displayed but the tree is right refreshed after iframe closure)_

**Comment by bvleur** [comment]
Am I right in not seeing any way to add new pages in the menu for now?
If you give me a short specification I can try to assist you in implementing,

**Comment by aflaus-presta** [comment]
Hi, thanks for your help.

@nicolas-bastien: what do you think about it ?

@bvleur: The page tree displayed in the page admin is different from the website menu admin.
The menu tree could be different from the page tree to get more flexibility. That why currently, you can not add new page directly from here.

Normally the tree browser allows you to create / edit menu element but one of the recent evolution should have introduce an error. All menu nodes are displayed as "not editable", maybe the problem comes from the fixtures.
